### ISSUE TITLE
Descriptions for individual shifts

### ISSUE THREAD

**Issue by itsrachelfish** [playatech/laravel-voldb#21]
Currently in laravel-voldb, it's only possible to have descriptions for departments. The existing Apogaea database allows descriptions for individual shifts and displays this information when viewing a department. This might be a nice addition to issue #10

**Comment by IzKen** [comment]
Same question as I had #31. If Shift is what we called a role for a dept before, then this is something we need.

In VolDB 2016 the roles all had a description, which is pretty important since people need to know what they are signing up for. Also some roles required a code, so the role description had the email address of who to contact. 

Screen shot:
![image](https://cloud.githubusercontent.com/assets/9004402/22268752/e55eb0c8-e245-11e6-8363-3ef476a92896.png)

**Comment by itsrachelfish** [comment]
Yep, "roles" in the old system are called "shifts" in this new database. :+1:

**Comment by itsrachelfish** [comment]
This has been fixed as a part of the updates for issue #31
